### ISSUE TITLE
DBに接続するときの手続きを共通化してほしい

### ISSUE THREAD

**Issue by aipacommander** [tak-tam/studyphp#1]
https://github.com/tak-tam/studyphp/blob/main/myapp/blog_index.php#L2
https://github.com/tak-tam/studyphp/blob/main/myapp/comment.php#L10
具体的な書き方はぐぐってほしいけど、例えば、ユーザー名を変更したい。パスワードを変更したいってなった場合、全部のファイルを変更する必要があるので面倒。なので、共通化すると良い

**Comment by tak-tam** [comment]
完了
