### ISSUE TITLE
スーパーグローバル変数へのアクセスの仕方について

### ISSUE THREAD

**Issue by aipacommander** [tak-tam/studyphp#2]
あるときから（忘れたけど）スーパーグローバル変数への直接の参照はやめたほうがいいってなりました。
https://www.php.net/manual/ja/language.variables.superglobals.php
https://github.com/tak-tam/studyphp/blob/main/myapp/post.php#L3
保守性とかの話になるので、もうちょい勉強したあとのフェーズなんだけど、今はとりあえず参照したら駄目なのねぐらいの感覚を覚えておくと良いです。
じゃあどうやってとるの？っての参考はこちら
https://teratail.com/questions/63786

**Comment by tak-tam** [comment]
完了
