### ISSUE TITLE
prepare statementが必要な理由の確認

### ISSUE THREAD

**Issue by aipacommander** [tak-tam/studyphp#3]
基本的に、SQL文へ変数や値をわたしたい場合はprepare -> executeメソッドの手続きを踏んだほうが良い
https://github.com/tak-tam/studyphp/blob/main/myapp/blog_index.php#L6
https://kinocolog.com/pdo_prepare/

**Comment by tak-tam** [comment]
完了

**Comment by aipacommander** [comment]
# head1

- list1
- list2
- list3
    - list4

関連するissueはこちら -> #2 

## head2
### head3
#### head4
##### head5

例）
https://github.com/tak-tam/studyphp/blob/study/myapp/blog_index.php#L7

修正しましたー

https://github.com/tak-tam/studyphp/blob/study/myapp/blog_index.php#L9-L12


![image](https://user-images.githubusercontent.com/6161879/123097172-d29c1b80-d46a-11eb-9eb8-fca0a517a9e4.png)
